### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by edoardohorse** [Jegogardo/Stack-Program#1]
- [ ] Aggiungere label con la versione del programma 
- [ ] Rinomina profilo
- [ ] Aggiunger barra di ricerca in "Sfoglia programmi"
- [ ] Modificare la posizione dei programmi (con evento Drag and Drop)
- [ ] Chiusura singola e multipla dei programmi
- [ ] Indicatore di apertura o chiusura di una programma
- [ ] Esportare i profili in un file batch
- [ ] Migliorare fetch dei programmi dal menu start
- [ ] Carica profili esternamente
- [ ] Refresh della UI con menu contestuali, icone e menu a tendina (ribbon)
- [x] Conto alla rovescia di 2 sec per avviare tutte le applicazioni, durante questo tempo viene mostrato il pulsante per annullare l'azione
- [x] Aggiungere button "Crea collegamento"
- [x] Aggiunta checkbox per chiudere l'applicazione dopo aver cliccato su Avvia tutti
- [x] Aggiungere collassa/espandi tutti i nodi nella searchApp
- [x] Listare (a toggle) i nodi per cartella o alfabeticamente nella searchApp
- [x] Ordinare i nodi alfabeticamente (asc/desc) in searchApp indipendentemente dall'organizzazione della lista
- [x] Application Reference (.appref-ms) come estensione nel openDialog
- [x] Ricordare ultima posizione nel openDialog
- [x] Controllo se il programma o il link è già presente nella lista, se si non lo aggiunge
- [x] Sfogliare tra i programmi installati e aggiungere i selezionati al profilo selezionato
- [x] Dare "checked" ai programmi già presenti nel profilo selezionato in "Sfoglia programmi"
- [x] Disabilitare i singoli o più programmi senza eliminarli
- [x] Abilitare i programmi disabilitati
- [x] Esportare file di configurazione
